### ISSUE TITLE
FE - 게시판 현재 issue

### ISSUE THREAD

**Issue by mick243** [PetMediSearch/PetMediSearch#71]
## 어떤 기능인가요?

게시판

## 작업 상세 내용

1. Post(게시글)를 출력할때 DB내용이 출력이 안됩니다.(PostList.tsx파일 문제로 추정)

2. react-quill 게시글 등록할때 게시글 내용 부분이 DB에 p태그가 포함된 채로 저장이 됩니다. 

3. 전체적인 스타일 미작성

4. Comment와 Category 미완성, Category 중복선택 비활성화 해야합니다.

5. CommentItem, CommentInput과 Detail.jsx, CreatePost.tsx 파일 로그인 인증 추가 및 DB로부터 데이터 받아오기 추가 필요

6. 댓글(Comment파일 안에 있는 내용)기능 아직 테스트를 못했습니다.

**Comment by hwinareun** [comment]
이슈, PR 제목 방식 지켜주시면 감사하겠습니다.
(FE, BE) [(키워드)] (작업 내용)
